version: "3"
services:
  server: &server
    image: kanalservis-testproject-server
    build: ./server
    env_file:
      - ./server/.env
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis

  qcluster:
    <<: *server
    command: poetry run python manage.py qcluster

  gunicorn:
    <<: *server
    ports:
      - "8888:8000"
    command: poetry run python -m gunicorn --workers 2 --bind 0.0.0.0:8000 core.wsgi:application

  daphne:
    <<: *server
    ports:
      - "8880:8008"
    command: poetry run python -m daphne -b 0.0.0.0 -p 8008 core.asgi:application

  client:
    image: kanalservis-testproject-client
    build: ./client
    ports:
      - "4200:80"
    depends_on:
      - server

  db:
    image: postgres
    env_file:
      - ./server/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
